## Max Threads use (right now only in 'get' module)
threads: 4

## Specify taped that are not allowed to use
## CAUTION: Applies only if 'lto-whitelist' is empty
lto-blacklist:
  - Z00001L5
  - Z00002L5

## Specify tapes which ONLY are allowed to use
## CAUTION: If you enter tapes here, lto-blacklist will be ignored. Only tapes from whitelist will be considered for writing
lto-whitelist:
#  - Y00001L5
#  - Y00002L5

## Specify tapelibrary and tapedrive devices
devices:
  tapelib: "/dev/sg5"
  tapedrive: "/dev/st0"

## Encryption key, make sure you save it somewhere else again
## If you loose it, no restore is possible
enc-key: ""

## Database name
database: "tapebackup.db"

## Path for database backup (SQL File into Git)
database-backup-git-path: "sql-backup"

## Remote server to sync data from
remote-server: "sever.example.com"

## Specify remote datadir and basedir
## basedir: will be stripped from remote-base-dir
## remote data and base direcotry must be an absolute path
remote-base-dir: "/mnt/bigDataStorage"
remote-data-dir: "/mnt/bigDataStorage/Videos"

## Specify maximum storage usage o local side (local-data-dir + local-enc-dir + local-verify-dir)
##   - In order to run correctly it must be more than one lto tape size
##   - On 'get' function it can only detect already over max_storage_size as the size is not calculated before download
##   - CAUTION: Defending on your filesystem and how many folders do you have, this can slowdown every operation seriously
## Use Number[Unit] (K/M/G/T/P/E or nothing for Byte), if nothing specified, it will be not limited by program
max_storage_usage:

## Specify local datadir and basedir
## local-base-dir is only necessary if you want to backup from local directory
local-base-dir: ""
local-data-dir: "test-download-dir"

## Specify directory where encrypted files are stored
local-enc-dir: "test-enc-dir"

## Specify verify dir (Should have minimum space of biggest file, ramdisk would be perfect)
local-verify-dir: "/tmp"

## Specify directory where tapedrive is mounted, will be used to write backups to
local-tape-mount-dir: "/mnt/tapedrive"

## Specify how many percent of files or count of files will be verified after writing to tape
## verify_files: "5%"
## verify_files: 20
verify-files: "5%"

## Directory to put files into on restore
restore-dir: "restore"
