# lto (ltfs) sizes in Bytes - 2G to be safe
lto-sizes:
  - LTO5: 1308693760000
lto-ignore-tapes:
  - Z00001L5
  - Z00002L5
devices:
  tapelib: "/dev/sg5"
  tapedrive: "/dev/st0"

database: "tapebackup.db"
database-backup-git-path: ""
remote-server: "sever.example.com"
remote-base-dir: "/mnt/bigDataStorage"
remote-data-dir: "/mnt/bigDataStorage/Videos"
local-data-dir: "test-download-dir"
local-enc-dir: "test-enc-dir"
local-tape-mount-dir: "/mnt/tapedrive"
enc-key: ""